name: Klubradio Feed Update
run-name: Klubradio Feed Update
on:
  schedule:
    - cron: '45 18,17,16,15,12,11,10,9,6 * * *'
  workflow_dispatch:
jobs:
  Create-New-Feed:
    name: Create New Feed
    runs-on: ubuntu-latest
    steps:
      - name: Crew
        uses: actions/checkout@v3
      - name: Create New Feed
        run: ./update-feed.sh
      - name: Commit and Push
        run: ./commit-feed.sh

