name: Check Shell Script
run-name: Check Shell Script
on:
  push:
    paths:
      - '**.sh'
  workflow_dispatch:
jobs:
  ShellCheck:
    name: Create New Feed
    runs-on: linux
    steps:
      - name: Check Shell Script
        run: shellcheck ./update-feed.sh